# Exce√ß√£o
    ü¢Ç evento que ocorre durante a execu√ß√£o do programa e que interrompe o fluxo normal de execu√ß√£o
    ü¢Ç em geral s√£o causadas por erros no codigo
        ‚Ä¢ exemplo: divis√£o por zero, tentar acessar uma vari√°vel que n√£o foi inicializada
    ü¢Ç ao lidar com exce√ß√µes, podemos exibir mensagens de erro ao usu√°rio e tentar corrigir o problema no c√≥digo.
    ü¢Ç tratamento de exe√ß√µes √© uma t√©cnica utilizada para lidar com esses erros, para que o programa n√£o pare abruptamente

## exemplos de exce√ß√£o
**exemplo de erro 1 - tentando acessar um elemento fora do indice de um array**
```.java
package exemplo1;
public class Ex1 {
	public static void main(String[] args) {
		int []  numeros = {1,2,3} ;
		System.out.println(numeros[3]); //ERRO ESPERADO : ArrayIndexOutOfBoundsException 
	}
}
```
**exemplo de erro 2 - divis√£o por zero**

```.java
package exemplo2;
public class Ex2 {
	public static void main(String[] args) {	
		int a = 10, b=0;
		System.out.println(a/b); //ERRO ESPERADO : ArithmeticException
	}
}
```

**exemplo de erro 3 - tentando converter uma string em um n√∫mero**
```.java
package exemplo2;
public class Ex3 {
	public static void main(String[] args) {
		String numero = "abc";
		int valor = Integer.parseInt(numero); // ERRO ESPERADO : NumberFormatException
	}
}

```

# Tratamento de exce√ß√µes
    ü¢Ç em java utiliza-se o bloco --> try - catch
    ü¢Ç try = onde escreve o c√≥digo que pode gerar uma exce√ß√£o
    ü¢Ç catch = onde escreve o c√≥digo que trata a exce√ß√£o

## exemplos de tratamento de exce√ß√µes
**Tratando erro 1**
```.java
package exemplo1;

public class Ex1 {

	public static void main(String[] args) {
		int []  numeros = {1,2,3};
		try { //TRATADA O ERRO COMO UMA EXCE√á√ÉO
		System.out.println(numeros[3]);
		} catch(Exception e) {
			System.out.println("Exce√ß√£o:" + e.getMessage()); //FORMAS DE MOSTRAR QUAL A EXE√á√ÉO - APENAS MOSTRAR O QUE ESTA ERRADO
			System.out.println("Exce√ß√£o:" + e.toString()); // MOSTRA O QUE ESTA ERRADO E QUAL √â O ERRO
		}
		
		System.out.println("o programa segue em excecu√ß√£o");
		System.out.println(numeros[3]); //FORA DO TRY, AQUI VAI GERAR UM ERRO FATAL 
		System.out.println("agora n√£o"); // AQUI J√Å N√ÉO √â MAIS EXECUTADO O PROGRAMA


	}

}

```
```.java
package exemplo1;

public class Ex1 {

	public static void main(String[] args) {
		int []  numeros = {1,2,3};
		try { //TRATADA O ERRO COMO UMA EXCE√á√ÉO
		System.out.println(numeros[2]);
		System.err.println("resultado"+(3/0));
		} catch(ArrayIndexOutOfBoundsException e) { // SE USAR DESSA MANEIRA ELE TRATA APENAS O ERRO ESPECIFICO - se ocorrer algum outro erro ele n√£o √© tratado 
			System.out.println("Exce√ß√£o:" + e.getMessage()); //FORMAS DE MOSTRAR QUAL A EXE√á√ÉO
			System.out.println("Exce√ß√£o:" + e.toString());
		}catch(Exception e ) { // TRATA O ERRO DE FORMA MAIS GENERICA
			System.out.println("Exce√ß√£o:" + e.toString());

		}
		
		System.out.println("o programa segue em excecu√ß√£o");
		System.out.println(numeros[3]); //FORA DO TRY, AQUI VAI GERAR UM ERRO FATAL 
		System.out.println("agora n√£o"); // AQUI J√Å N√ÉO √â MAIS EXECUTADO O PROGRAMA


	}

}

```

**tratando erro 2**
```.java
package exemplo2;
public class Ex2 {
	public static void main(String[] args) {
		int a = 10, b=0;
		try {
		System.out.println(a/b); //ERRO ESPERADO : ArithmeticException
		}catch(ArithmeticException e) {
			System.out.println("Exce√ß√£o: "+e.toString());
		}
		System.out.println("CONTINUA");
	}
}

```
**tratando erro 3**
```.java
package exemplo2;
public class Ex3 {
	public static void main(String[] args) {
		String numero = "abc";
		try {
		int valor = Integer.parseInt(numero); // ERRO ESPERADO : NumberFormatException
		}catch(NumberFormatException e){
			System.out.println("exce√ß√£o: "+e.toString() );
		}
		System.out.println("CONTINUA");
	}
}

```
